/*
 * AI Support package
 * 
 * WARNING: Use the new one below!
 * An alternative file below "AI-REST.js", enables both Gemini or Chat GPT via REST API's without the Java jar packages being loaded.
 * 
 * Requires:
 *   * jArchi - https://www.archimatetool.com/blog/2018/07/02/jarchi/
 *   * Gemini API Java Libraries:
 *     * https://repo1.maven.org/maven2/commons-logging/commons-logging/1.3.5/commons-logging-1.3.5.jar
 *     * https://repo1.maven.org/maven2/com/google/auth/google-auth-library-credentials/1.37.1/google-auth-library-credentials-1.37.1.jar
 *     * https://repo1.maven.org/maven2/com/google/auth/google-auth-library-oauth2-http/1.37.1/google-auth-library-oauth2-http-1.37.1.jar
 *     * https://repo1.maven.org/maven2/com/google/genai/google-genai/1.5.0/google-genai-1.5.0.jar
 *     * https://repo1.maven.org/maven2/com/google/guava/guava/33.4.8-jre/guava-33.4.8-jre.jar
 *     * https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5/httpclient-4.5.jar
 *     * https://repo1.maven.org/maven2/org/apache/httpcomponents/client5/httpclient5/5.5/httpclient5-5.5.jar
 *     * https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
 *     * https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.19.1/jackson-annotations-2.19.1.jar
 *     * https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.19.1/jackson-core-2.19.1.jar
 *     * https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.19.1/jackson-databind-2.19.1.jar
 *     * https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.19.1/jackson-datatype-jdk8-2.19.1.jar
 *     * https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.19.1/jackson-datatype-jsr310-2.19.1.jar
 * 
 *  Gemini API Key - https://ai.google.dev/gemini-api/docs/api-key
 * 
 * Version 1: Gemini API
 * 
 * (c) 2025 Steven Mileham
 *
 */
const geminiKey = "{{INSERT KEY HERE}}";

Java.addToClasspath(__DIR__ +"/jars/google-genai-1.5.0.jar");
Java.addToClasspath(__DIR__ +"/jars/jackson-core-2.19.1.jar");
Java.addToClasspath(__DIR__ +"/jars/jackson-databind-2.19.1.jar");
Java.addToClasspath(__DIR__ +"/jars/guava-33.4.8-jre.jar");
Java.addToClasspath(__DIR__ +"/jars/httpclient-4.5.14.jar");
Java.addToClasspath(__DIR__ +"/jars/httpcore-4.4.16.jar");
Java.addToClasspath(__DIR__ +"/jars/google-auth-library-credentials-1.37.1.jar");
Java.addToClasspath(__DIR__ +"/jars/google-auth-library-oauth2-http-1.37.1.jar");
Java.addToClasspath(__DIR__ +"/jars/jackson-datatype-jdk8-2.19.1.jar");
Java.addToClasspath(__DIR__ +"/jars/jackson-datatype-jsr310-2.19.1.jar");
Java.addToClasspath(__DIR__ +"/jars/jackson-annotations-2.19.1.jar");
Java.addToClasspath(__DIR__ +"/jars/commons-logging-1.3.5.jar");

console.log("Loaded Gemini Package")

const sendToAI = (thePrompt) => {
    var client = Java.type("com.google.genai.Client");
    let theclient = client.builder().apiKey(geminiKey).build();

    let  response =
            theclient.models.generateContent(
                "gemini-2.5-flash",
                `${thePrompt}`,
                null);

    let aiOutput = response.text();
    return `${aiOutput}\n\nGenerated by Gemini ${new Date().toLocaleString()}`;
}

module.exports=sendToAI;